using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;
using HydroNumerics.MikeSheTools.PFS.SheFile;

namespace HydroNumerics.MikeSheTools.PFS.NWK11
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class branch1: PFSMapper
  {


    internal branch1(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
        case "points":
          points = new POINTS(sub);
          break;
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }

    }

    public branch1()
    {
      _pfsHandle = new PFSSection("branch1");

      points = new POINTS();
      _pfsHandle.AddSection(points._pfsHandle);

      _pfsHandle.AddKeyword(new PFSKeyword("name", PFSParameterType.String, ""));
    }

    public POINTS points{get; private set;}

    public string name1
    {
      get
      {
        return _pfsHandle.GetKeyword("name", 1).GetParameter(1).ToString();
      }
      set
      {
        _pfsHandle.GetKeyword("name", 1).GetParameter(1).Value = value;
      }
    }

  }
}
