using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;
using HydroNumerics.MikeSheTools.PFS.SheFile;

namespace HydroNumerics.MikeSheTools.PFS.NWK11
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class connections
  {

    private PFSKeyword _keyword;

    internal connections(PFSKeyword keyword)
    {
       _keyword = keyword;
    }

    public connections()
    {
       _keyword = new PFSKeyword("connections");
       _keyword.AddParameter(new PFSParameter(PFSParameterType.String));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Double));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.String));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Double));
    }
    public string Par1
    {
      get { return _keyword.GetParameter(1).ToString();}
      set { _keyword.GetParameter(1).Value = value;}
    }

    public double Par2
    {
      get { return _keyword.GetParameter(2).ToDouble();}
      set { _keyword.GetParameter(2).Value = value;}
    }

    public string Par3
    {
      get { return _keyword.GetParameter(3).ToString();}
      set { _keyword.GetParameter(3).Value = value;}
    }

    public double Par4
    {
      get { return _keyword.GetParameter(4).ToDouble();}
      set { _keyword.GetParameter(4).Value = value;}
    }

  }
}
