using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;
using HydroNumerics.MikeSheTools.PFS.SheFile;

namespace HydroNumerics.MikeSheTools.PFS.NWK11
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class POINTS: PFSMapper
  {


    internal POINTS(PFSSection Section)
    {
      _pfsHandle = Section;

      points = new List<point>();
      for (int i = 1; i <= Section.GetKeywordsNo("point"); i++)
        points.Add(new point(Section.GetKeyword("point",i)));
      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }

    }

    public POINTS(string pfsname)
    {
      _pfsHandle = new PFSSection(pfsname);

      points = new List<point>();
    }

    public List<point> points {get; private set;}
  }
}
