using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;
using HydroNumerics.MikeSheTools.PFS.SheFile;

namespace HydroNumerics.MikeSheTools.PFS.NWK11
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class STRUCTURE_MODULE: PFSMapper
  {


    internal STRUCTURE_MODULE(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
        case "CROSSSECTIONS":
          CROSSSECTIONS = new CROSSSECTIONS(sub);
          break;
        case "WEIR":
          WEIR = new WEIR(sub);
          break;
        case "CULVERTS":
          CULVERTS = new WEIR(sub);
          break;
        case "PUMPS":
          PUMPS = new WEIR(sub);
          break;
        case "REGULATING_STR":
          REGULATING_STR = new WEIR(sub);
          break;
        case "CONTROL_STR":
          CONTROL_STR = new WEIR(sub);
          break;
        case "DAMBREAK_STR":
          DAMBREAK_STR = new WEIR(sub);
          break;
        case "BRIDGE":
          BRIDGE = new WEIR(sub);
          break;
        case "USER_DEFINED":
          USER_DEFINED = new WEIR(sub);
          break;
        case "TABULATED":
          TABULATED = new WEIR(sub);
          break;
        case "ENERGYBALANCE":
          ENERGYBALANCE = new WEIR(sub);
          break;
        case "MIKE12_HYDRAU":
          MIKE12_HYDRAU = new WEIR(sub);
          break;
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }

      Structure_Version = new Structure_Version(_pfsHandle.GetKeyword("Structure_Version", 1));
    }

    public STRUCTURE_MODULE()
    {
      _pfsHandle = new PFSSection("STRUCTURE_MODULE");

      CROSSSECTIONS = new CROSSSECTIONS();
      _pfsHandle.AddSection(CROSSSECTIONS._pfsHandle);

      WEIR = new WEIR();
      _pfsHandle.AddSection(WEIR._pfsHandle);

      CULVERTS = new WEIR();
      _pfsHandle.AddSection(CULVERTS._pfsHandle);

      PUMPS = new WEIR();
      _pfsHandle.AddSection(PUMPS._pfsHandle);

      REGULATING_STR = new WEIR();
      _pfsHandle.AddSection(REGULATING_STR._pfsHandle);

      CONTROL_STR = new WEIR();
      _pfsHandle.AddSection(CONTROL_STR._pfsHandle);

      DAMBREAK_STR = new WEIR();
      _pfsHandle.AddSection(DAMBREAK_STR._pfsHandle);

      BRIDGE = new WEIR();
      _pfsHandle.AddSection(BRIDGE._pfsHandle);

      USER_DEFINED = new WEIR();
      _pfsHandle.AddSection(USER_DEFINED._pfsHandle);

      TABULATED = new WEIR();
      _pfsHandle.AddSection(TABULATED._pfsHandle);

      ENERGYBALANCE = new WEIR();
      _pfsHandle.AddSection(ENERGYBALANCE._pfsHandle);

      MIKE12_HYDRAU = new WEIR();
      _pfsHandle.AddSection(MIKE12_HYDRAU._pfsHandle);

    }

    public CROSSSECTIONS CROSSSECTIONS{get; private set;}

    public WEIR WEIR{get; private set;}

    public WEIR CULVERTS{get; private set;}

    public WEIR PUMPS{get; private set;}

    public WEIR REGULATING_STR{get; private set;}

    public WEIR CONTROL_STR{get; private set;}

    public WEIR DAMBREAK_STR{get; private set;}

    public WEIR BRIDGE{get; private set;}

    public WEIR USER_DEFINED{get; private set;}

    public WEIR TABULATED{get; private set;}

    public WEIR ENERGYBALANCE{get; private set;}

    public WEIR MIKE12_HYDRAU{get; private set;}

    public Structure_Version Structure_Version{get; private set;}
  }
}
