using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;
using HydroNumerics.MikeSheTools.PFS.SheFile;

namespace HydroNumerics.MikeSheTools.PFS.Well
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class WELLDATA: PFSMapper
  {


    internal WELLDATA(PFSSection Section)
    {
      _pfsHandle = Section;

      WELLNO_1s = new List<WELLNO_1>();
      WELLNO_1190s = new List<WELLNO_1190>();
      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
          default:
            if (sub.Name.Substring(0,6).Equals("WELLNO"))
            {
              WELLNO_1s.Add(new WELLNO_1(sub));
              break;
            }
            if (sub.Name.Substring(0,6).Equals("WELLNO"))
            {
              WELLNO_1190s.Add(new WELLNO_1190(sub));
              break;
            }
            _unMappedSections.Add(sub.Name);
          break;
        }
      }

    }

    public WELLDATA(string pfsname)
    {
      _pfsHandle = new PFSSection(pfsname);

      WELLNO_1s = new List<WELLNO_1>();
      WELLNO_1190s = new List<WELLNO_1190>();
      _pfsHandle.AddKeyword(new PFSKeyword("Touched", PFSParameterType.Integer, 0));

      _pfsHandle.AddKeyword(new PFSKeyword("NoWells", PFSParameterType.Integer, 0));

      _pfsHandle.AddKeyword(new PFSKeyword("IncludeFractureWell", PFSParameterType.Integer, 0));

    }

    public List<WELLNO_1> WELLNO_1s {get; private set;}

    public List<WELLNO_1190> WELLNO_1190s {get; private set;}

    public int Touched
    {
      get
      {
        return _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).Value = value;
      }
    }

    public int NoWells
    {
      get
      {
        return _pfsHandle.GetKeyword("NoWells", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("NoWells", 1).GetParameter(1).Value = value;
      }
    }

    public int IncludeFractureWell
    {
      get
      {
        return _pfsHandle.GetKeyword("IncludeFractureWell", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("IncludeFractureWell", 1).GetParameter(1).Value = value;
      }
    }

  }
}
