using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;
using HydroNumerics.MikeSheTools.PFS.SheFile;

namespace HydroNumerics.MikeSheTools.PFS.NWK11
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class NWK11File: PFSFile
  {

    private MIKE_11_Network_editor _mIKE_11_Network_editor;

    public NWK11File(string filename)
      : base(filename)
    {
      _mIKE_11_Network_editor = new MIKE_11_Network_editor(_pfsClass.GetTarget(1));
    }


    public MIKE_11_Network_editor MIKE_11_Network_editor
    {
     get { return _mIKE_11_Network_editor; }
     private set {_mIKE_11_Network_editor = value; }
    }

  }
}
