//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 3.0.40818.0
// 
namespace DataConnectorUI2.XAMLServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XAMLParameters", Namespace="http://schemas.datacontract.org/2004/07/DataConnectorWCF")]
    public partial struct XAMLParameters : System.ComponentModel.INotifyPropertyChanged {
        
        private string pointsField;
        
        private string querytypeField;
        
        private double radiusField;
        
        private double reduceField;
        
        private string tableField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string points {
            get {
                return this.pointsField;
            }
            set {
                if ((object.ReferenceEquals(this.pointsField, value) != true)) {
                    this.pointsField = value;
                    this.RaisePropertyChanged("points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string querytype {
            get {
                return this.querytypeField;
            }
            set {
                if ((object.ReferenceEquals(this.querytypeField, value) != true)) {
                    this.querytypeField = value;
                    this.RaisePropertyChanged("querytype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double radius {
            get {
                return this.radiusField;
            }
            set {
                if ((this.radiusField.Equals(value) != true)) {
                    this.radiusField = value;
                    this.RaisePropertyChanged("radius");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double reduce {
            get {
                return this.reduceField;
            }
            set {
                if ((this.reduceField.Equals(value) != true)) {
                    this.reduceField = value;
                    this.RaisePropertyChanged("reduce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string table {
            get {
                return this.tableField;
            }
            set {
                if ((object.ReferenceEquals(this.tableField, value) != true)) {
                    this.tableField = value;
                    this.RaisePropertyChanged("table");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XAMLResponse", Namespace="http://schemas.datacontract.org/2004/07/DataConnectorWCF")]
    public partial class XAMLResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ErrorCodeField;
        
        private System.Collections.ObjectModel.ObservableCollection<DataConnectorUI2.XAMLServiceReference.XAMLFields> OutputFieldsField;
        
        private string OutputMessageField;
        
        private double QueryTimeField;
        
        private string XAMLField;
        
        private int totalPointsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<DataConnectorUI2.XAMLServiceReference.XAMLFields> OutputFields {
            get {
                return this.OutputFieldsField;
            }
            set {
                if ((object.ReferenceEquals(this.OutputFieldsField, value) != true)) {
                    this.OutputFieldsField = value;
                    this.RaisePropertyChanged("OutputFields");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OutputMessage {
            get {
                return this.OutputMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.OutputMessageField, value) != true)) {
                    this.OutputMessageField = value;
                    this.RaisePropertyChanged("OutputMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double QueryTime {
            get {
                return this.QueryTimeField;
            }
            set {
                if ((this.QueryTimeField.Equals(value) != true)) {
                    this.QueryTimeField = value;
                    this.RaisePropertyChanged("QueryTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XAML {
            get {
                return this.XAMLField;
            }
            set {
                if ((object.ReferenceEquals(this.XAMLField, value) != true)) {
                    this.XAMLField = value;
                    this.RaisePropertyChanged("XAML");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int totalPoints {
            get {
                return this.totalPointsField;
            }
            set {
                if ((this.totalPointsField.Equals(value) != true)) {
                    this.totalPointsField = value;
                    this.RaisePropertyChanged("totalPoints");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XAMLFields", Namespace="http://schemas.datacontract.org/2004/07/DataConnectorWCF")]
    public partial struct XAMLFields : System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.Generic.Dictionary<string, string> FieldsField;
        
        private string IDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Fields {
            get {
                return this.FieldsField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldsField, value) != true)) {
                    this.FieldsField = value;
                    this.RaisePropertyChanged("Fields");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="XAMLServiceReference.IXAML")]
    public interface IXAML {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IXAML/GetSQLDataXAML", ReplyAction="http://tempuri.org/IXAML/GetSQLDataXAMLResponse")]
        System.IAsyncResult BeginGetSQLDataXAML(DataConnectorUI2.XAMLServiceReference.XAMLParameters Parameters, System.AsyncCallback callback, object asyncState);
        
        DataConnectorUI2.XAMLServiceReference.XAMLResponse EndGetSQLDataXAML(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IXAMLChannel : DataConnectorUI2.XAMLServiceReference.IXAML, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetSQLDataXAMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSQLDataXAMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public DataConnectorUI2.XAMLServiceReference.XAMLResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((DataConnectorUI2.XAMLServiceReference.XAMLResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class XAMLClient : System.ServiceModel.ClientBase<DataConnectorUI2.XAMLServiceReference.IXAML>, DataConnectorUI2.XAMLServiceReference.IXAML {
        
        private BeginOperationDelegate onBeginGetSQLDataXAMLDelegate;
        
        private EndOperationDelegate onEndGetSQLDataXAMLDelegate;
        
        private System.Threading.SendOrPostCallback onGetSQLDataXAMLCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public XAMLClient() {
        }
        
        public XAMLClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XAMLClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XAMLClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XAMLClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetSQLDataXAMLCompletedEventArgs> GetSQLDataXAMLCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult DataConnectorUI2.XAMLServiceReference.IXAML.BeginGetSQLDataXAML(DataConnectorUI2.XAMLServiceReference.XAMLParameters Parameters, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSQLDataXAML(Parameters, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataConnectorUI2.XAMLServiceReference.XAMLResponse DataConnectorUI2.XAMLServiceReference.IXAML.EndGetSQLDataXAML(System.IAsyncResult result) {
            return base.Channel.EndGetSQLDataXAML(result);
        }
        
        private System.IAsyncResult OnBeginGetSQLDataXAML(object[] inValues, System.AsyncCallback callback, object asyncState) {
            DataConnectorUI2.XAMLServiceReference.XAMLParameters Parameters = ((DataConnectorUI2.XAMLServiceReference.XAMLParameters)(inValues[0]));
            return ((DataConnectorUI2.XAMLServiceReference.IXAML)(this)).BeginGetSQLDataXAML(Parameters, callback, asyncState);
        }
        
        private object[] OnEndGetSQLDataXAML(System.IAsyncResult result) {
            DataConnectorUI2.XAMLServiceReference.XAMLResponse retVal = ((DataConnectorUI2.XAMLServiceReference.IXAML)(this)).EndGetSQLDataXAML(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSQLDataXAMLCompleted(object state) {
            if ((this.GetSQLDataXAMLCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSQLDataXAMLCompleted(this, new GetSQLDataXAMLCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSQLDataXAMLAsync(DataConnectorUI2.XAMLServiceReference.XAMLParameters Parameters) {
            this.GetSQLDataXAMLAsync(Parameters, null);
        }
        
        public void GetSQLDataXAMLAsync(DataConnectorUI2.XAMLServiceReference.XAMLParameters Parameters, object userState) {
            if ((this.onBeginGetSQLDataXAMLDelegate == null)) {
                this.onBeginGetSQLDataXAMLDelegate = new BeginOperationDelegate(this.OnBeginGetSQLDataXAML);
            }
            if ((this.onEndGetSQLDataXAMLDelegate == null)) {
                this.onEndGetSQLDataXAMLDelegate = new EndOperationDelegate(this.OnEndGetSQLDataXAML);
            }
            if ((this.onGetSQLDataXAMLCompletedDelegate == null)) {
                this.onGetSQLDataXAMLCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSQLDataXAMLCompleted);
            }
            base.InvokeAsync(this.onBeginGetSQLDataXAMLDelegate, new object[] {
                        Parameters}, this.onEndGetSQLDataXAMLDelegate, this.onGetSQLDataXAMLCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override DataConnectorUI2.XAMLServiceReference.IXAML CreateChannel() {
            return new XAMLClientChannel(this);
        }
        
        private class XAMLClientChannel : ChannelBase<DataConnectorUI2.XAMLServiceReference.IXAML>, DataConnectorUI2.XAMLServiceReference.IXAML {
            
            public XAMLClientChannel(System.ServiceModel.ClientBase<DataConnectorUI2.XAMLServiceReference.IXAML> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetSQLDataXAML(DataConnectorUI2.XAMLServiceReference.XAMLParameters Parameters, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = Parameters;
                System.IAsyncResult _result = base.BeginInvoke("GetSQLDataXAML", _args, callback, asyncState);
                return _result;
            }
            
            public DataConnectorUI2.XAMLServiceReference.XAMLResponse EndGetSQLDataXAML(System.IAsyncResult result) {
                object[] _args = new object[0];
                DataConnectorUI2.XAMLServiceReference.XAMLResponse _result = ((DataConnectorUI2.XAMLServiceReference.XAMLResponse)(base.EndInvoke("GetSQLDataXAML", _args, result)));
                return _result;
            }
        }
    }
}
