using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;
using HydroNumerics.MikeSheTools.PFS.SheFile;

namespace HydroNumerics.MikeSheTools.PFS.Well
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class GEOMETRY: PFSMapper
  {


    internal GEOMETRY(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }

    }

    public GEOMETRY(string pfsname)
    {
      _pfsHandle = new PFSSection(pfsname);

      _pfsHandle.AddKeyword(new PFSKeyword("x0", PFSParameterType.Integer, 0));

      _pfsHandle.AddKeyword(new PFSKeyword("y0", PFSParameterType.Integer, 0));

      _pfsHandle.AddKeyword(new PFSKeyword("x1", PFSParameterType.Integer, 0));

      _pfsHandle.AddKeyword(new PFSKeyword("y1", PFSParameterType.Integer, 0));

      _pfsHandle.AddKeyword(new PFSKeyword("OverlayFilename", PFSParameterType.FileName, ""));

    }

    public int x0
    {
      get
      {
        return _pfsHandle.GetKeyword("x0", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("x0", 1).GetParameter(1).Value = value;
      }
    }

    public int y0
    {
      get
      {
        return _pfsHandle.GetKeyword("y0", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("y0", 1).GetParameter(1).Value = value;
      }
    }

    public int x1
    {
      get
      {
        return _pfsHandle.GetKeyword("x1", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("x1", 1).GetParameter(1).Value = value;
      }
    }

    public int y1
    {
      get
      {
        return _pfsHandle.GetKeyword("y1", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("y1", 1).GetParameter(1).Value = value;
      }
    }

    public string OverlayFilename
    {
      get
      {
        return _pfsHandle.GetKeyword("OverlayFilename", 1).GetParameter(1).ToString();
      }
      set
      {
        _pfsHandle.GetKeyword("OverlayFilename", 1).GetParameter(1).Value = value;
      }
    }

  }
}
