using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;
using HydroNumerics.MikeSheTools.PFS.SheFile;

namespace HydroNumerics.MikeSheTools.PFS.MEX
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class COMPUTATIONAL_ENGINE_CONTROL: PFSMapper
  {

    private RO_POSTPROCESS_LEVEL _rO_POSTPROCESS_LEVEL;
    private HD_RUNTIME_LEVEL _hD_RUNTIME_LEVEL;
    private EVALUATION_MATRIX _eVALUATION_MATRIX;

    internal COMPUTATIONAL_ENGINE_CONTROL(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
        case "RO_POSTPROCESS_LEVEL":
          _rO_POSTPROCESS_LEVEL = new RO_POSTPROCESS_LEVEL(sub);
          break;
        case "HD_RUNTIME_LEVEL":
          _hD_RUNTIME_LEVEL = new HD_RUNTIME_LEVEL(sub);
          break;
        case "EVALUATION_MATRIX":
          _eVALUATION_MATRIX = new EVALUATION_MATRIX(sub);
          break;
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public RO_POSTPROCESS_LEVEL RO_POSTPROCESS_LEVEL
    {
     get { return _rO_POSTPROCESS_LEVEL; }
    }

    public HD_RUNTIME_LEVEL HD_RUNTIME_LEVEL
    {
     get { return _hD_RUNTIME_LEVEL; }
    }

    public EVALUATION_MATRIX EVALUATION_MATRIX
    {
     get { return _eVALUATION_MATRIX; }
    }

    public string SEC_ID
    {
      get
      {
        return _pfsHandle.GetKeyword("SEC_ID", 1).GetParameter(1).ToString();
      }
      set
      {
        _pfsHandle.GetKeyword("SEC_ID", 1).GetParameter(1).Value = value;
      }
    }

  }
}
