using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;
using HydroNumerics.MikeSheTools.PFS.SheFile;

namespace HydroNumerics.MikeSheTools.PFS.MEX
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class COMPUTATIONAL_ENGINE_CONTROL: PFSMapper
  {


    internal COMPUTATIONAL_ENGINE_CONTROL(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
        case "RO_POSTPROCESS_LEVEL":
          RO_POSTPROCESS_LEVEL = new RO_POSTPROCESS_LEVEL(sub);
          break;
        case "HD_RUNTIME_LEVEL":
          HD_RUNTIME_LEVEL = new HD_RUNTIME_LEVEL(sub);
          break;
        case "EVALUATION_MATRIX":
          EVALUATION_MATRIX = new EVALUATION_MATRIX(sub);
          break;
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }

    }

    public COMPUTATIONAL_ENGINE_CONTROL(string pfsname)
    {
      _pfsHandle = new PFSSection(pfsname);

      _pfsHandle.AddKeyword(new PFSKeyword("SEC_ID", PFSParameterType.String, ""));

      RO_POSTPROCESS_LEVEL = new RO_POSTPROCESS_LEVEL("RO_POSTPROCESS_LEVEL" );
      _pfsHandle.AddSection(RO_POSTPROCESS_LEVEL._pfsHandle);

      HD_RUNTIME_LEVEL = new HD_RUNTIME_LEVEL("HD_RUNTIME_LEVEL" );
      _pfsHandle.AddSection(HD_RUNTIME_LEVEL._pfsHandle);

      EVALUATION_MATRIX = new EVALUATION_MATRIX("EVALUATION_MATRIX" );
      _pfsHandle.AddSection(EVALUATION_MATRIX._pfsHandle);

    }

    public RO_POSTPROCESS_LEVEL RO_POSTPROCESS_LEVEL{get; private set;}

    public HD_RUNTIME_LEVEL HD_RUNTIME_LEVEL{get; private set;}

    public EVALUATION_MATRIX EVALUATION_MATRIX{get; private set;}

    public string SEC_ID
    {
      get
      {
        return _pfsHandle.GetKeyword("SEC_ID", 1).GetParameter(1).ToString();
      }
      set
      {
        _pfsHandle.GetKeyword("SEC_ID", 1).GetParameter(1).Value = value;
      }
    }

  }
}
