using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;
using HydroNumerics.MikeSheTools.PFS.SheFile;

namespace HydroNumerics.MikeSheTools.PFS.MEX
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class FRC_INFLOW: PFSMapper
  {

    private OPERATOR _oPERATOR;

    internal FRC_INFLOW(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
        case "OPERATOR":
          _oPERATOR = new OPERATOR(sub);
          break;
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public OPERATOR OPERATOR
    {
     get { return _oPERATOR; }
    }

    public string LOCATION_TYPE
    {
      get
      {
        return _pfsHandle.GetKeyword("LOCATION_TYPE", 1).GetParameter(1).ToString();
      }
      set
      {
        _pfsHandle.GetKeyword("LOCATION_TYPE", 1).GetParameter(1).Value = value;
      }
    }

    public string LOCATION
    {
      get
      {
        return _pfsHandle.GetKeyword("LOCATION", 1).GetParameter(1).ToString();
      }
      set
      {
        _pfsHandle.GetKeyword("LOCATION", 1).GetParameter(1).Value = value;
      }
    }

  }
}
