using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;
using HydroNumerics.MikeSheTools.PFS.SheFile;

namespace HydroNumerics.MikeSheTools.PFS.MEX
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class GLOBAL_PARAMETERS: PFSMapper
  {


    internal GLOBAL_PARAMETERS(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }

    }

    public GLOBAL_PARAMETERS()
    {
      _pfsHandle = new PFSSection("GLOBAL_PARAMETERS");

      _pfsHandle.AddKeyword(new PFSKeyword("SYNTAX_VERSION", PFSParameterType.Integer, 0));
      _pfsHandle.AddKeyword(new PFSKeyword("UNIT_TYPE", PFSParameterType.Integer, 0));
      _pfsHandle.AddKeyword(new PFSKeyword("Calibration_Method", PFSParameterType.Integer, 0));
      _pfsHandle.AddKeyword(new PFSKeyword("WriteConvergenceFile", PFSParameterType.Boolean, true));
      _pfsHandle.AddKeyword(new PFSKeyword("MaxNoModelEvaluations", PFSParameterType.Integer, 0));
      _pfsHandle.AddKeyword(new PFSKeyword("NoComplexes", PFSParameterType.Integer, 0));
      _pfsHandle.AddKeyword(new PFSKeyword("NoPointsComplex", PFSParameterType.Integer, 0));
      _pfsHandle.AddKeyword(new PFSKeyword("NoPointsSubComplex", PFSParameterType.Integer, 0));
      _pfsHandle.AddKeyword(new PFSKeyword("NoEvolutionSteps", PFSParameterType.Integer, 0));
      _pfsHandle.AddKeyword(new PFSKeyword("StopNoLoops", PFSParameterType.Integer, 0));
      _pfsHandle.AddKeyword(new PFSKeyword("MinChange", PFSParameterType.Double, 0));
      _pfsHandle.AddKeyword(new PFSKeyword("Delta", PFSParameterType.Double, 0));
      _pfsHandle.AddKeyword(new PFSKeyword("PEPS", PFSParameterType.Double, 0));
      _pfsHandle.AddKeyword(new PFSKeyword("NormalizeObj", PFSParameterType.Boolean, true));
      _pfsHandle.AddKeyword(new PFSKeyword("EvalWaterBalance", PFSParameterType.Boolean, true));
      _pfsHandle.AddKeyword(new PFSKeyword("EvalRMSE", PFSParameterType.Boolean, true));
      _pfsHandle.AddKeyword(new PFSKeyword("EvalPeak", PFSParameterType.Boolean, true));
      _pfsHandle.AddKeyword(new PFSKeyword("EvalPeak_Value", PFSParameterType.Integer, 0));
      _pfsHandle.AddKeyword(new PFSKeyword("EvalLow", PFSParameterType.Boolean, true));
      _pfsHandle.AddKeyword(new PFSKeyword("EvalLow_Value", PFSParameterType.Integer, 0));
      _pfsHandle.AddKeyword(new PFSKeyword("EvalPeak_WB", PFSParameterType.Boolean, true));
      _pfsHandle.AddKeyword(new PFSKeyword("EvalPeak_WB_Value", PFSParameterType.Integer, 0));
    }

    public int SYNTAX_VERSION1
    {
      get
      {
        return _pfsHandle.GetKeyword("SYNTAX_VERSION", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("SYNTAX_VERSION", 1).GetParameter(1).Value = value;
      }
    }

    public int UNIT_TYPE1
    {
      get
      {
        return _pfsHandle.GetKeyword("UNIT_TYPE", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("UNIT_TYPE", 1).GetParameter(1).Value = value;
      }
    }

    public int Calibration_Method1
    {
      get
      {
        return _pfsHandle.GetKeyword("Calibration_Method", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Calibration_Method", 1).GetParameter(1).Value = value;
      }
    }

    public bool WriteConvergenceFile1
    {
      get
      {
        return _pfsHandle.GetKeyword("WriteConvergenceFile", 1).GetParameter(1).ToBoolean();
      }
      set
      {
        _pfsHandle.GetKeyword("WriteConvergenceFile", 1).GetParameter(1).Value = value;
      }
    }

    public int MaxNoModelEvaluations1
    {
      get
      {
        return _pfsHandle.GetKeyword("MaxNoModelEvaluations", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("MaxNoModelEvaluations", 1).GetParameter(1).Value = value;
      }
    }

    public int NoComplexes1
    {
      get
      {
        return _pfsHandle.GetKeyword("NoComplexes", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("NoComplexes", 1).GetParameter(1).Value = value;
      }
    }

    public int NoPointsComplex1
    {
      get
      {
        return _pfsHandle.GetKeyword("NoPointsComplex", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("NoPointsComplex", 1).GetParameter(1).Value = value;
      }
    }

    public int NoPointsSubComplex1
    {
      get
      {
        return _pfsHandle.GetKeyword("NoPointsSubComplex", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("NoPointsSubComplex", 1).GetParameter(1).Value = value;
      }
    }

    public int NoEvolutionSteps1
    {
      get
      {
        return _pfsHandle.GetKeyword("NoEvolutionSteps", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("NoEvolutionSteps", 1).GetParameter(1).Value = value;
      }
    }

    public int StopNoLoops1
    {
      get
      {
        return _pfsHandle.GetKeyword("StopNoLoops", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("StopNoLoops", 1).GetParameter(1).Value = value;
      }
    }

    public double MinChange1
    {
      get
      {
        return _pfsHandle.GetKeyword("MinChange", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("MinChange", 1).GetParameter(1).Value = value;
      }
    }

    public double Delta1
    {
      get
      {
        return _pfsHandle.GetKeyword("Delta", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("Delta", 1).GetParameter(1).Value = value;
      }
    }

    public double PEPS1
    {
      get
      {
        return _pfsHandle.GetKeyword("PEPS", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("PEPS", 1).GetParameter(1).Value = value;
      }
    }

    public bool NormalizeObj1
    {
      get
      {
        return _pfsHandle.GetKeyword("NormalizeObj", 1).GetParameter(1).ToBoolean();
      }
      set
      {
        _pfsHandle.GetKeyword("NormalizeObj", 1).GetParameter(1).Value = value;
      }
    }

    public bool EvalWaterBalance1
    {
      get
      {
        return _pfsHandle.GetKeyword("EvalWaterBalance", 1).GetParameter(1).ToBoolean();
      }
      set
      {
        _pfsHandle.GetKeyword("EvalWaterBalance", 1).GetParameter(1).Value = value;
      }
    }

    public bool EvalRMSE1
    {
      get
      {
        return _pfsHandle.GetKeyword("EvalRMSE", 1).GetParameter(1).ToBoolean();
      }
      set
      {
        _pfsHandle.GetKeyword("EvalRMSE", 1).GetParameter(1).Value = value;
      }
    }

    public bool EvalPeak1
    {
      get
      {
        return _pfsHandle.GetKeyword("EvalPeak", 1).GetParameter(1).ToBoolean();
      }
      set
      {
        _pfsHandle.GetKeyword("EvalPeak", 1).GetParameter(1).Value = value;
      }
    }

    public int EvalPeak_Value1
    {
      get
      {
        return _pfsHandle.GetKeyword("EvalPeak_Value", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("EvalPeak_Value", 1).GetParameter(1).Value = value;
      }
    }

    public bool EvalLow1
    {
      get
      {
        return _pfsHandle.GetKeyword("EvalLow", 1).GetParameter(1).ToBoolean();
      }
      set
      {
        _pfsHandle.GetKeyword("EvalLow", 1).GetParameter(1).Value = value;
      }
    }

    public int EvalLow_Value1
    {
      get
      {
        return _pfsHandle.GetKeyword("EvalLow_Value", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("EvalLow_Value", 1).GetParameter(1).Value = value;
      }
    }

    public bool EvalPeak_WB1
    {
      get
      {
        return _pfsHandle.GetKeyword("EvalPeak_WB", 1).GetParameter(1).ToBoolean();
      }
      set
      {
        _pfsHandle.GetKeyword("EvalPeak_WB", 1).GetParameter(1).Value = value;
      }
    }

    public int EvalPeak_WB_Value1
    {
      get
      {
        return _pfsHandle.GetKeyword("EvalPeak_WB_Value", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("EvalPeak_WB_Value", 1).GetParameter(1).Value = value;
      }
    }

  }
}
