using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;
using HydroNumerics.MikeSheTools.PFS.SheFile;

namespace HydroNumerics.MikeSheTools.PFS.MEX
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class HD_RUNTIME_LEVEL: PFSMapper
  {

    private STOP_CRITERION1 _sTOP_CRITERION;

    internal HD_RUNTIME_LEVEL(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
        case "STOP_CRITERION":
          _sTOP_CRITERION = new STOP_CRITERION1(sub);
          break;
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public STOP_CRITERION1 STOP_CRITERION
    {
     get { return _sTOP_CRITERION; }
    }

  }
}
