using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;
using HydroNumerics.MikeSheTools.PFS.SheFile;

namespace HydroNumerics.MikeSheTools.PFS.MEX
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class INITIAL_CONDITION_SELECTION: PFSMapper
  {

    private HOTSTART_FILE _hOTSTART_FILE;

    internal INITIAL_CONDITION_SELECTION(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
        case "HOTSTART_FILE":
          _hOTSTART_FILE = new HOTSTART_FILE(sub);
          break;
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public HOTSTART_FILE HOTSTART_FILE
    {
     get { return _hOTSTART_FILE; }
    }

    public string IC_ID
    {
      get
      {
        return _pfsHandle.GetKeyword("IC_ID", 1).GetParameter(1).ToString();
      }
      set
      {
        _pfsHandle.GetKeyword("IC_ID", 1).GetParameter(1).Value = value;
      }
    }

  }
}
