using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;
using HydroNumerics.MikeSheTools.PFS.SheFile;

namespace HydroNumerics.MikeSheTools.PFS.MEX
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class msm_SRQ: PFSMapper
  {

    private Metadata _metadata;
    private Rows _rows;

    internal msm_SRQ(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
        case "Metadata":
          _metadata = new Metadata(sub);
          break;
        case "Rows":
          _rows = new Rows(sub);
          break;
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public Metadata Metadata
    {
     get { return _metadata; }
    }

    public Rows Rows
    {
     get { return _rows; }
    }

  }
}
