using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;
using HydroNumerics.MikeSheTools.PFS.SheFile;

namespace HydroNumerics.MikeSheTools.PFS.MEX
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class SRC_SELECTION_CRITERION: PFSMapper
  {


    internal SRC_SELECTION_CRITERION(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }

      SRC_FLOW = new SRC_FLOW(_pfsHandle.GetKeyword("SRC_FLOW", 1));
    }

    public SRC_SELECTION_CRITERION(string pfsname)
    {
      _pfsHandle = new PFSSection(pfsname);

      SRC_FLOW = new SRC_FLOW("SRC_FLOW");
      _pfsHandle.AddKeyword(SRC_FLOW._keyword);
    }

    public SRC_FLOW SRC_FLOW{get; private set;}
  }
}
