//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 3.0.40818.0
// 
namespace DataConnectorUI2.WKTServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WKTParameters", Namespace="http://schemas.datacontract.org/2004/07/DataConnectorWCF")]
    public partial struct WKTParameters : System.ComponentModel.INotifyPropertyChanged {
        
        private string pointsField;
        
        private string querytypeField;
        
        private double radiusField;
        
        private double reduceField;
        
        private string tableField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string points {
            get {
                return this.pointsField;
            }
            set {
                if ((object.ReferenceEquals(this.pointsField, value) != true)) {
                    this.pointsField = value;
                    this.RaisePropertyChanged("points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string querytype {
            get {
                return this.querytypeField;
            }
            set {
                if ((object.ReferenceEquals(this.querytypeField, value) != true)) {
                    this.querytypeField = value;
                    this.RaisePropertyChanged("querytype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double radius {
            get {
                return this.radiusField;
            }
            set {
                if ((this.radiusField.Equals(value) != true)) {
                    this.radiusField = value;
                    this.RaisePropertyChanged("radius");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double reduce {
            get {
                return this.reduceField;
            }
            set {
                if ((this.reduceField.Equals(value) != true)) {
                    this.reduceField = value;
                    this.RaisePropertyChanged("reduce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string table {
            get {
                return this.tableField;
            }
            set {
                if ((object.ReferenceEquals(this.tableField, value) != true)) {
                    this.tableField = value;
                    this.RaisePropertyChanged("table");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WKTResponse", Namespace="http://schemas.datacontract.org/2004/07/DataConnectorWCF")]
    public partial class WKTResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ErrorCodeField;
        
        private string OutputMessageField;
        
        private System.Collections.ObjectModel.ObservableCollection<DataConnectorUI2.WKTServiceReference.WKTShape> OutputShapesField;
        
        private double QueryTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OutputMessage {
            get {
                return this.OutputMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.OutputMessageField, value) != true)) {
                    this.OutputMessageField = value;
                    this.RaisePropertyChanged("OutputMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<DataConnectorUI2.WKTServiceReference.WKTShape> OutputShapes {
            get {
                return this.OutputShapesField;
            }
            set {
                if ((object.ReferenceEquals(this.OutputShapesField, value) != true)) {
                    this.OutputShapesField = value;
                    this.RaisePropertyChanged("OutputShapes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double QueryTime {
            get {
                return this.QueryTimeField;
            }
            set {
                if ((this.QueryTimeField.Equals(value) != true)) {
                    this.QueryTimeField = value;
                    this.RaisePropertyChanged("QueryTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WKTShape", Namespace="http://schemas.datacontract.org/2004/07/DataConnectorWCF")]
    public partial struct WKTShape : System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.Generic.Dictionary<string, string> FieldsField;
        
        private string IDField;
        
        private string WKTField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Fields {
            get {
                return this.FieldsField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldsField, value) != true)) {
                    this.FieldsField = value;
                    this.RaisePropertyChanged("Fields");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WKT {
            get {
                return this.WKTField;
            }
            set {
                if ((object.ReferenceEquals(this.WKTField, value) != true)) {
                    this.WKTField = value;
                    this.RaisePropertyChanged("WKT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WKTServiceReference.IWKT")]
    public interface IWKT {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWKT/GetSQLDataWKT", ReplyAction="http://tempuri.org/IWKT/GetSQLDataWKTResponse")]
        System.IAsyncResult BeginGetSQLDataWKT(DataConnectorUI2.WKTServiceReference.WKTParameters Parameters, System.AsyncCallback callback, object asyncState);
        
        DataConnectorUI2.WKTServiceReference.WKTResponse EndGetSQLDataWKT(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IWKTChannel : DataConnectorUI2.WKTServiceReference.IWKT, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetSQLDataWKTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSQLDataWKTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public DataConnectorUI2.WKTServiceReference.WKTResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((DataConnectorUI2.WKTServiceReference.WKTResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WKTClient : System.ServiceModel.ClientBase<DataConnectorUI2.WKTServiceReference.IWKT>, DataConnectorUI2.WKTServiceReference.IWKT {
        
        private BeginOperationDelegate onBeginGetSQLDataWKTDelegate;
        
        private EndOperationDelegate onEndGetSQLDataWKTDelegate;
        
        private System.Threading.SendOrPostCallback onGetSQLDataWKTCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WKTClient() {
        }
        
        public WKTClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WKTClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WKTClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WKTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetSQLDataWKTCompletedEventArgs> GetSQLDataWKTCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult DataConnectorUI2.WKTServiceReference.IWKT.BeginGetSQLDataWKT(DataConnectorUI2.WKTServiceReference.WKTParameters Parameters, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSQLDataWKT(Parameters, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataConnectorUI2.WKTServiceReference.WKTResponse DataConnectorUI2.WKTServiceReference.IWKT.EndGetSQLDataWKT(System.IAsyncResult result) {
            return base.Channel.EndGetSQLDataWKT(result);
        }
        
        private System.IAsyncResult OnBeginGetSQLDataWKT(object[] inValues, System.AsyncCallback callback, object asyncState) {
            DataConnectorUI2.WKTServiceReference.WKTParameters Parameters = ((DataConnectorUI2.WKTServiceReference.WKTParameters)(inValues[0]));
            return ((DataConnectorUI2.WKTServiceReference.IWKT)(this)).BeginGetSQLDataWKT(Parameters, callback, asyncState);
        }
        
        private object[] OnEndGetSQLDataWKT(System.IAsyncResult result) {
            DataConnectorUI2.WKTServiceReference.WKTResponse retVal = ((DataConnectorUI2.WKTServiceReference.IWKT)(this)).EndGetSQLDataWKT(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSQLDataWKTCompleted(object state) {
            if ((this.GetSQLDataWKTCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSQLDataWKTCompleted(this, new GetSQLDataWKTCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSQLDataWKTAsync(DataConnectorUI2.WKTServiceReference.WKTParameters Parameters) {
            this.GetSQLDataWKTAsync(Parameters, null);
        }
        
        public void GetSQLDataWKTAsync(DataConnectorUI2.WKTServiceReference.WKTParameters Parameters, object userState) {
            if ((this.onBeginGetSQLDataWKTDelegate == null)) {
                this.onBeginGetSQLDataWKTDelegate = new BeginOperationDelegate(this.OnBeginGetSQLDataWKT);
            }
            if ((this.onEndGetSQLDataWKTDelegate == null)) {
                this.onEndGetSQLDataWKTDelegate = new EndOperationDelegate(this.OnEndGetSQLDataWKT);
            }
            if ((this.onGetSQLDataWKTCompletedDelegate == null)) {
                this.onGetSQLDataWKTCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSQLDataWKTCompleted);
            }
            base.InvokeAsync(this.onBeginGetSQLDataWKTDelegate, new object[] {
                        Parameters}, this.onEndGetSQLDataWKTDelegate, this.onGetSQLDataWKTCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override DataConnectorUI2.WKTServiceReference.IWKT CreateChannel() {
            return new WKTClientChannel(this);
        }
        
        private class WKTClientChannel : ChannelBase<DataConnectorUI2.WKTServiceReference.IWKT>, DataConnectorUI2.WKTServiceReference.IWKT {
            
            public WKTClientChannel(System.ServiceModel.ClientBase<DataConnectorUI2.WKTServiceReference.IWKT> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetSQLDataWKT(DataConnectorUI2.WKTServiceReference.WKTParameters Parameters, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = Parameters;
                System.IAsyncResult _result = base.BeginInvoke("GetSQLDataWKT", _args, callback, asyncState);
                return _result;
            }
            
            public DataConnectorUI2.WKTServiceReference.WKTResponse EndGetSQLDataWKT(System.IAsyncResult result) {
                object[] _args = new object[0];
                DataConnectorUI2.WKTServiceReference.WKTResponse _result = ((DataConnectorUI2.WKTServiceReference.WKTResponse)(base.EndInvoke("GetSQLDataWKT", _args, result)));
                return _result;
            }
        }
    }
}
