using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;
using HydroNumerics.MikeSheTools.PFS.SheFile;

namespace HydroNumerics.MikeSheTools.PFS.NWK11
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class BRANCHES: PFSMapper
  {


    internal BRANCHES(PFSSection Section)
    {
      _pfsHandle = Section;

      branchs = new List<branch>();
      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
          default:
            if (sub.Name.Substring(0,6).Equals("branch"))
            {
              branchs.Add(new branch(sub));
              break;
            }
            _unMappedSections.Add(sub.Name);
          break;
        }
      }

    }

    public BRANCHES(string pfsname)
    {
      _pfsHandle = new PFSSection(pfsname);

      branchs = new List<branch>();
    }

    public List<branch> branchs {get; private set;}

  }
}
