using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;
using HydroNumerics.MikeSheTools.PFS.SheFile;

namespace HydroNumerics.MikeSheTools.PFS.NWK11
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class DataFileName
  {

    private PFSKeyword _keyword;

    internal DataFileName(PFSKeyword keyword)
    {
       _keyword = keyword;
    }

    public DataFileName()
    {
       _keyword = new PFSKeyword("DataFileName");
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Integer));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.FileName));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.String));
    }
    public int Par1
    {
      get { return _keyword.GetParameter(1).ToInt();}
      set { _keyword.GetParameter(1).Value = value;}
    }

    public string Par2
    {
      get { return _keyword.GetParameter(2).ToString();}
      set { _keyword.GetParameter(2).Value = value;}
    }

    public string Par3
    {
      get { return _keyword.GetParameter(3).ToString();}
      set { _keyword.GetParameter(3).Value = value;}
    }

  }
}
