using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;
using HydroNumerics.MikeSheTools.PFS.SheFile;

namespace HydroNumerics.MikeSheTools.PFS.NWK11
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class Elevation_Parameters: PFSMapper
  {


    internal Elevation_Parameters(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
        case "QH_Relations":
          QH_Relations = new WEIR(sub);
          break;
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }

    }

    public Elevation_Parameters(string pfsname)
    {
      _pfsHandle = new PFSSection(pfsname);

      QH_Relations = new WEIR("QH_Relations" );
      _pfsHandle.AddSection(QH_Relations._pfsHandle);

    }

    public WEIR QH_Relations{get; private set;}

  }
}
