using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;
using HydroNumerics.MikeSheTools.PFS.SheFile;

namespace HydroNumerics.MikeSheTools.PFS.NWK11
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class point
  {

    private PFSKeyword _keyword;

    internal point(PFSKeyword keyword)
    {
       _keyword = keyword;
    }

    public point()
    {
       _keyword = new PFSKeyword("point");
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Integer));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Double));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Double));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Integer));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Double));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Integer));
    }
    public int Par1
    {
      get { return _keyword.GetParameter(1).ToInt();}
      set { _keyword.GetParameter(1).Value = value;}
    }

    public double Par2
    {
      get { return _keyword.GetParameter(2).ToDouble();}
      set { _keyword.GetParameter(2).Value = value;}
    }

    public double Par3
    {
      get { return _keyword.GetParameter(3).ToDouble();}
      set { _keyword.GetParameter(3).Value = value;}
    }

    public int Par4
    {
      get { return _keyword.GetParameter(4).ToInt();}
      set { _keyword.GetParameter(4).Value = value;}
    }

    public double Par5
    {
      get { return _keyword.GetParameter(5).ToDouble();}
      set { _keyword.GetParameter(5).Value = value;}
    }

    public int Par6
    {
      get { return _keyword.GetParameter(6).ToInt();}
      set { _keyword.GetParameter(6).Value = value;}
    }

  }
}
