using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;
using HydroNumerics.MikeSheTools.PFS.SheFile;

namespace HydroNumerics.MikeSheTools.PFS.MEX
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class BBOUNDARY
  {

    internal PFSKeyword _keyword;

    internal BBOUNDARY(PFSKeyword keyword)
    {
       _keyword = keyword;
    }

    public BBOUNDARY(string keywordname)
    {
       _keyword = new PFSKeyword(keywordname);
       _keyword.AddParameter(new PFSParameter(PFSParameterType.String, ""));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Integer, 0));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Integer, 0));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Integer, 0));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Integer, 0));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Integer, 0));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Missing, ""));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Missing, ""));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Integer, 0));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.String, ""));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.String, ""));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Integer, 0));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.String, ""));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.String, ""));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Integer, 0));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.String, ""));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Integer, 0));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Double, 0));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Integer, 0));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Integer, 0));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Integer, 0));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Missing, ""));
    }
    public string Par1
    {
      get { return _keyword.GetParameter(1).ToString();}
      set { _keyword.GetParameter(1).Value = value;}
    }

    public int Par2
    {
      get { return _keyword.GetParameter(2).ToInt();}
      set { _keyword.GetParameter(2).Value = value;}
    }

    public int Par3
    {
      get { return _keyword.GetParameter(3).ToInt();}
      set { _keyword.GetParameter(3).Value = value;}
    }

    public int Par4
    {
      get { return _keyword.GetParameter(4).ToInt();}
      set { _keyword.GetParameter(4).Value = value;}
    }

    public int Par5
    {
      get { return _keyword.GetParameter(5).ToInt();}
      set { _keyword.GetParameter(5).Value = value;}
    }

    public int Par6
    {
      get { return _keyword.GetParameter(6).ToInt();}
      set { _keyword.GetParameter(6).Value = value;}
    }

    public string Par7
    {
      get { return _keyword.GetParameter(7).ToString();}
      set { _keyword.GetParameter(7).Value = value;}
    }

    public string Par8
    {
      get { return _keyword.GetParameter(8).ToString();}
      set { _keyword.GetParameter(8).Value = value;}
    }

    public int Par9
    {
      get { return _keyword.GetParameter(9).ToInt();}
      set { _keyword.GetParameter(9).Value = value;}
    }

    public string Par10
    {
      get { return _keyword.GetParameter(10).ToString();}
      set { _keyword.GetParameter(10).Value = value;}
    }

    public string Par11
    {
      get { return _keyword.GetParameter(11).ToString();}
      set { _keyword.GetParameter(11).Value = value;}
    }

    public int Par12
    {
      get { return _keyword.GetParameter(12).ToInt();}
      set { _keyword.GetParameter(12).Value = value;}
    }

    public string Par13
    {
      get { return _keyword.GetParameter(13).ToString();}
      set { _keyword.GetParameter(13).Value = value;}
    }

    public string Par14
    {
      get { return _keyword.GetParameter(14).ToString();}
      set { _keyword.GetParameter(14).Value = value;}
    }

    public int Par15
    {
      get { return _keyword.GetParameter(15).ToInt();}
      set { _keyword.GetParameter(15).Value = value;}
    }

    public string Par16
    {
      get { return _keyword.GetParameter(16).ToString();}
      set { _keyword.GetParameter(16).Value = value;}
    }

    public int Par17
    {
      get { return _keyword.GetParameter(17).ToInt();}
      set { _keyword.GetParameter(17).Value = value;}
    }

    public double Par18
    {
      get { return _keyword.GetParameter(18).ToDouble();}
      set { _keyword.GetParameter(18).Value = value;}
    }

    public int Par19
    {
      get { return _keyword.GetParameter(19).ToInt();}
      set { _keyword.GetParameter(19).Value = value;}
    }

    public int Par20
    {
      get { return _keyword.GetParameter(20).ToInt();}
      set { _keyword.GetParameter(20).Value = value;}
    }

    public int Par21
    {
      get { return _keyword.GetParameter(21).ToInt();}
      set { _keyword.GetParameter(21).Value = value;}
    }

    public string Par22
    {
      get { return _keyword.GetParameter(22).ToString();}
      set { _keyword.GetParameter(22).Value = value;}
    }

  }
}
