using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;
using HydroNumerics.MikeSheTools.PFS.SheFile;

namespace HydroNumerics.MikeSheTools.PFS.MEX
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class CALIBRATION_SPECIFICATION: PFSMapper
  {

    private GLOBAL_PARAMETERS _gLOBAL_PARAMETERS;
    private MODEL_A _mODEL_A;
    private MODEL_B _mODEL_B;
    private MODEL_C1_C2 _mODEL_C1_C2;
    private MEASUREMENTS _mEASUREMENTS;

    internal CALIBRATION_SPECIFICATION(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
        case "GLOBAL_PARAMETERS":
          _gLOBAL_PARAMETERS = new GLOBAL_PARAMETERS(sub);
          break;
        case "MODEL_A":
          _mODEL_A = new MODEL_A(sub);
          break;
        case "MODEL_B":
          _mODEL_B = new MODEL_B(sub);
          break;
        case "MODEL_C1_C2":
          _mODEL_C1_C2 = new MODEL_C1_C2(sub);
          break;
        case "MEASUREMENTS":
          _mEASUREMENTS = new MEASUREMENTS(sub);
          break;
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public GLOBAL_PARAMETERS GLOBAL_PARAMETERS
    {
     get { return _gLOBAL_PARAMETERS; }
    }

    public MODEL_A MODEL_A
    {
     get { return _mODEL_A; }
    }

    public MODEL_B MODEL_B
    {
     get { return _mODEL_B; }
    }

    public MODEL_C1_C2 MODEL_C1_C2
    {
     get { return _mODEL_C1_C2; }
    }

    public MEASUREMENTS MEASUREMENTS
    {
     get { return _mEASUREMENTS; }
    }

  }
}
