using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;
using HydroNumerics.MikeSheTools.PFS.SheFile;

namespace HydroNumerics.MikeSheTools.PFS.MEX
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class Cross_Section1: PFSMapper
  {


    internal Cross_Section1(PFSSection Section)
    {
      _pfsHandle = Section;

      ProcessDatas = new List<ProcessData>();
      for (int i = 1; i <= Section.GetKeywordsNo("ProcessData"); i++)
        ProcessDatas.Add(new ProcessData(Section.GetKeyword("ProcessData",i)));
      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }

    }

    public Cross_Section1(string pfsname)
    {
      _pfsHandle = new PFSSection(pfsname);

      ProcessDatas = new List<ProcessData>();
      _pfsHandle.AddKeyword(new PFSKeyword("CRSID", PFSParameterType.String, ""));

      _pfsHandle.AddKeyword(new PFSKeyword("TypeNo", PFSParameterType.Integer, 0));

      _pfsHandle.AddKeyword(new PFSKeyword("Description", PFSParameterType.Missing, ""));

    }

    public List<ProcessData> ProcessDatas {get; private set;}
    public string CRSID
    {
      get
      {
        return _pfsHandle.GetKeyword("CRSID", 1).GetParameter(1).ToString();
      }
      set
      {
        _pfsHandle.GetKeyword("CRSID", 1).GetParameter(1).Value = value;
      }
    }

    public int TypeNo
    {
      get
      {
        return _pfsHandle.GetKeyword("TypeNo", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("TypeNo", 1).GetParameter(1).Value = value;
      }
    }

    public string Description
    {
      get
      {
        return _pfsHandle.GetKeyword("Description", 1).GetParameter(1).ToString();
      }
      set
      {
        _pfsHandle.GetKeyword("Description", 1).GetParameter(1).Value = value;
      }
    }

  }
}
