using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;
using HydroNumerics.MikeSheTools.PFS.SheFile;

namespace HydroNumerics.MikeSheTools.PFS.MEX
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class HOTSTART_FILE: PFSMapper
  {

    private SRC_SELECTION_CRITERION _sRC_SELECTION_CRITERION;

    internal HOTSTART_FILE(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
        case "SRC_SELECTION_CRITERION":
          _sRC_SELECTION_CRITERION = new SRC_SELECTION_CRITERION(sub);
          break;
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public SRC_SELECTION_CRITERION SRC_SELECTION_CRITERION
    {
     get { return _sRC_SELECTION_CRITERION; }
    }

    public string HOTSTART_FILE1
    {
      get
      {
        return _pfsHandle.GetKeyword("HOTSTART_FILE", 1).GetParameter(1).ToString();
      }
      set
      {
        _pfsHandle.GetKeyword("HOTSTART_FILE", 1).GetParameter(1).Value = value;
      }
    }

    public string START_DATE
    {
      get
      {
        return _pfsHandle.GetKeyword("START_DATE", 1).GetParameter(1).ToString();
      }
      set
      {
        _pfsHandle.GetKeyword("START_DATE", 1).GetParameter(1).Value = value;
      }
    }

    public string PERIOD
    {
      get
      {
        return _pfsHandle.GetKeyword("PERIOD", 1).GetParameter(1).ToString();
      }
      set
      {
        _pfsHandle.GetKeyword("PERIOD", 1).GetParameter(1).Value = value;
      }
    }

  }
}
