using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;
using HydroNumerics.MikeSheTools.PFS.SheFile;

namespace HydroNumerics.MikeSheTools.PFS.MEX
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class HOTSTART_FILE: PFSMapper
  {


    internal HOTSTART_FILE(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
        case "SRC_SELECTION_CRITERION":
          SRC_SELECTION_CRITERION = new SRC_SELECTION_CRITERION(sub);
          break;
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }

    }

    public HOTSTART_FILE(string pfsname)
    {
      _pfsHandle = new PFSSection(pfsname);

      _pfsHandle.AddKeyword(new PFSKeyword("HOTSTART_FILE", PFSParameterType.String, ""));

      _pfsHandle.AddKeyword(new PFSKeyword("START_DATE", PFSParameterType.String, ""));

      _pfsHandle.AddKeyword(new PFSKeyword("PERIOD", PFSParameterType.String, ""));

      SRC_SELECTION_CRITERION = new SRC_SELECTION_CRITERION("SRC_SELECTION_CRITERION" );
      _pfsHandle.AddSection(SRC_SELECTION_CRITERION._pfsHandle);

    }

    public SRC_SELECTION_CRITERION SRC_SELECTION_CRITERION{get; private set;}

    public string HOTSTART_FILE1
    {
      get
      {
        return _pfsHandle.GetKeyword("HOTSTART_FILE", 1).GetParameter(1).ToString();
      }
      set
      {
        _pfsHandle.GetKeyword("HOTSTART_FILE", 1).GetParameter(1).Value = value;
      }
    }

    public string START_DATE
    {
      get
      {
        return _pfsHandle.GetKeyword("START_DATE", 1).GetParameter(1).ToString();
      }
      set
      {
        _pfsHandle.GetKeyword("START_DATE", 1).GetParameter(1).Value = value;
      }
    }

    public string PERIOD
    {
      get
      {
        return _pfsHandle.GetKeyword("PERIOD", 1).GetParameter(1).ToString();
      }
      set
      {
        _pfsHandle.GetKeyword("PERIOD", 1).GetParameter(1).Value = value;
      }
    }

  }
}
