using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;
using HydroNumerics.MikeSheTools.PFS.SheFile;

namespace HydroNumerics.MikeSheTools.PFS.MEX
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class Metadata: PFSMapper
  {


    internal Metadata(PFSSection Section)
    {
      _pfsHandle = Section;

      Fields = new List<Field>();
      for (int i = 1; i <= Section.GetKeywordsNo("Field"); i++)
        Fields.Add(new Field(Section.GetKeyword("Field",i)));
      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }

    }

    public Metadata(string pfsname)
    {
      _pfsHandle = new PFSSection(pfsname);

      Fields = new List<Field>();
    }

    public List<Field> Fields {get; private set;}
  }
}
