using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;
using HydroNumerics.MikeSheTools.PFS.SheFile;

namespace HydroNumerics.MikeSheTools.PFS.MEX
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class msm_WQProcess: PFSMapper
  {

    private Metadata3 _metadata;
    private Rows3 _rows;

    internal msm_WQProcess(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
        case "Metadata":
          _metadata = new Metadata3(sub);
          break;
        case "Rows":
          _rows = new Rows3(sub);
          break;
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public Metadata3 Metadata
    {
     get { return _metadata; }
    }

    public Rows3 Rows
    {
     get { return _rows; }
    }

  }
}
