using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;
using HydroNumerics.MikeSheTools.PFS.SheFile;

namespace HydroNumerics.MikeSheTools.PFS.MEX
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class OPERATOR: PFSMapper
  {


    internal OPERATOR(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public string OPERATOR_TYPE
    {
      get
      {
        return _pfsHandle.GetKeyword("OPERATOR_TYPE", 1).GetParameter(1).ToString();
      }
      set
      {
        _pfsHandle.GetKeyword("OPERATOR_TYPE", 1).GetParameter(1).Value = value;
      }
    }

    public string T_RETENTION
    {
      get
      {
        return _pfsHandle.GetKeyword("T_RETENTION", 1).GetParameter(1).ToString();
      }
      set
      {
        _pfsHandle.GetKeyword("T_RETENTION", 1).GetParameter(1).Value = value;
      }
    }

  }
}
