using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;
using HydroNumerics.MikeSheTools.PFS.SheFile;

namespace HydroNumerics.MikeSheTools.PFS.MEX
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class Pump
  {

    private PFSKeyword _keyword;

    internal Pump(PFSKeyword keyword)
    {
       _keyword = keyword;
    }

    public Pump()
    {
       _keyword = new PFSKeyword("Pump");
       _keyword.AddParameter(new PFSParameter(PFSParameterType.String));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.String));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.String));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Integer));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.String));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Integer));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Double));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Double));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Integer));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Integer));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Integer));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Missing));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Missing));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Missing));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Missing));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.String));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Missing));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.String));
       _keyword.AddParameter(new PFSParameter(PFSParameterType.Missing));
    }
    public string Par1
    {
      get { return _keyword.GetParameter(1).ToString();}
      set { _keyword.GetParameter(1).Value = value;}
    }

    public string Par2
    {
      get { return _keyword.GetParameter(2).ToString();}
      set { _keyword.GetParameter(2).Value = value;}
    }

    public string Par3
    {
      get { return _keyword.GetParameter(3).ToString();}
      set { _keyword.GetParameter(3).Value = value;}
    }

    public int Par4
    {
      get { return _keyword.GetParameter(4).ToInt();}
      set { _keyword.GetParameter(4).Value = value;}
    }

    public string Par5
    {
      get { return _keyword.GetParameter(5).ToString();}
      set { _keyword.GetParameter(5).Value = value;}
    }

    public int Par6
    {
      get { return _keyword.GetParameter(6).ToInt();}
      set { _keyword.GetParameter(6).Value = value;}
    }

    public double Par7
    {
      get { return _keyword.GetParameter(7).ToDouble();}
      set { _keyword.GetParameter(7).Value = value;}
    }

    public double Par8
    {
      get { return _keyword.GetParameter(8).ToDouble();}
      set { _keyword.GetParameter(8).Value = value;}
    }

    public int Par9
    {
      get { return _keyword.GetParameter(9).ToInt();}
      set { _keyword.GetParameter(9).Value = value;}
    }

    public int Par10
    {
      get { return _keyword.GetParameter(10).ToInt();}
      set { _keyword.GetParameter(10).Value = value;}
    }

    public int Par11
    {
      get { return _keyword.GetParameter(11).ToInt();}
      set { _keyword.GetParameter(11).Value = value;}
    }

    public string Par12
    {
      get { return _keyword.GetParameter(12).ToString();}
      set { _keyword.GetParameter(12).Value = value;}
    }

    public string Par13
    {
      get { return _keyword.GetParameter(13).ToString();}
      set { _keyword.GetParameter(13).Value = value;}
    }

    public string Par14
    {
      get { return _keyword.GetParameter(14).ToString();}
      set { _keyword.GetParameter(14).Value = value;}
    }

    public string Par15
    {
      get { return _keyword.GetParameter(15).ToString();}
      set { _keyword.GetParameter(15).Value = value;}
    }

    public string Par16
    {
      get { return _keyword.GetParameter(16).ToString();}
      set { _keyword.GetParameter(16).Value = value;}
    }

    public string Par17
    {
      get { return _keyword.GetParameter(17).ToString();}
      set { _keyword.GetParameter(17).Value = value;}
    }

    public string Par18
    {
      get { return _keyword.GetParameter(18).ToString();}
      set { _keyword.GetParameter(18).Value = value;}
    }

    public string Par19
    {
      get { return _keyword.GetParameter(19).ToString();}
      set { _keyword.GetParameter(19).Value = value;}
    }

  }
}
