using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;
using HydroNumerics.MikeSheTools.PFS.SheFile;

namespace HydroNumerics.MikeSheTools.PFS.MEX
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class STOP_CRITERION1: PFSMapper
  {

    private TOTAL_VOLUME _tOTAL_VOLUME;

    internal STOP_CRITERION1(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
        case "TOTAL_VOLUME":
          _tOTAL_VOLUME = new TOTAL_VOLUME(sub);
          break;
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public TOTAL_VOLUME TOTAL_VOLUME
    {
     get { return _tOTAL_VOLUME; }
    }

    public string CRITERION_ID
    {
      get
      {
        return _pfsHandle.GetKeyword("CRITERION_ID", 1).GetParameter(1).ToString();
      }
      set
      {
        _pfsHandle.GetKeyword("CRITERION_ID", 1).GetParameter(1).Value = value;
      }
    }

  }
}
